### ISSUE TITLE
A Git Branch Structure For Theme Releases

### ISSUE THREAD

**Issue by thombruce** [hugomodo/hugomodo#8]
We shall have a [standalone] branch on themes where appropriate**.

** It isn’t appropriate on HugoModo for instance, because it includes no further submodules.

	HugoModo
		[master]
	HugoModo Best Motherfucking Website
		[master]
		**[standalone]**

The plan also remains to add release branches:

	HugoModo
		[master]
		**[0.0.1]**
		**[0.1.0]**
	HugoModo Best Motherfucking Website
		[master]
		[standalone]
		**[0.0.1]**
		**[0.1.0]**

These are based on [master], so standalone should have variants:

	HugoModo
		[master]
		[0.0.1]
		[0.1.0]
	HugoModo Best Motherfucking Website
		[master]
		[standalone]
		[0.0.1]
		[0.1.0]
		**[0.0.1-standalone]**
		**[0.1.0-standalone]**

I have also considered having [latest] and [latest-standalone] branches, so that devs may use the latest stable versions. This is only a problem however if [master] and [standalone] are unstable, which should not be the case if we use a [develop] branch as detailed below (this is one fewer branch to manage).

And we should also move development work to a [develop] branch:

	HugoModo
		[master]
		**[develop]**
		[0.0.1]
		[0.1.0]
	HugoModo Best Motherfucking Website
		[master]
		**[develop]**
		[standalone]
		[0.0.1]
		[0.1.0]
		[0.0.1-standalone]
		[0.1.0-standalone]

Finally, some kind of hook should exist that - when we merge [develop] to [master] - updates [standalone].

A further function should exist for releasing versioned branches:

	[master] <- [develop] = [0.0.1]
	[standalone] <- [develop] = [0.0.1-standalone]

Note also the files/directories that must be changed/ignored:

	.gitmodules
	config.toml -> [themes]
	themes/

(.gitmodules and themes/ only present on [standalone], config.toml -> [themes] reflects that path to theme is nested)

**Comment by thombruce** [comment]
What say we... ignore standalone for now and merely focus on versioned branches?

```
HugoModo
	[master]
	[develop]
	[0.0.1]
	[0.1.0]
HugoModo Best Motherfucking Website
	[master]
	[develop]
	[0.0.1]
	[0.1.0]
```

This way, no files need ignored/modified. We merely...

```
[master] <- [develop] = [0.1]
```

**Comment by thombruce** [comment]
## Themes and Extensions

These are the themes and extensions which exist at present:

### Themes
- HugoModo
- HugoModo Best Motherfucking Website
- HugoModo Bootstrap
- HugoModo Milligram
- HugoModo Picnic

### Extensions

- HugoModo Cookie Consent
- HugoModo FuseJS
- HugoModo Image Processing
- HugoModo Shortcode Partials

## For each...

- [x] A `master` branch should exist
- [ ] A `develop` branch should exist
- [ ] A `0.1` branch should exist

- `master` and `0.1` should be stable.
- Any merge into `master` should be reflected in the release of a versioned (`0.1`) branch

### Additional Considerations

This is, in effect, [A Successful Git Branching Model](https://nvie.com/posts/a-successful-git-branching-model/). But that model has some drawbacks...

Since feature branches are merged into develop rather than into release candidate branches, develop may need to be rolled back following incompatible merges.

Perhaps it would be preferable to forego the `develop` branch and instead...

1. Branch from `master` into `feature/some-feature`
2. Merge `feature` branches into a `release-0.1` branch
3. Merge `release-0.1` into `0.1` and `master`, completing a release

## Keep it on `master`?

I much prefer this for open source projects, so that `master` remains not only the branch that new features are branched off of but also the branch which PRs are submitted for.

If we consider `master` central to our strategy...

```
master -> feature/my-feature -> PR to master
```

...at which point, it would be preferable to not merge directly into master but to have a branch based on master that may be tested.

Travis CI have got our back here: https://docs.travis-ci.com/user/pull-requests/

I expect other CI services do the same.

We do miss out on getting actual eyes on the change, but that can be achieved manually as so:

```
PR to master -> pull respective feature branch to local -> then either...

1. merge --squash into master
2. merge into temp branch based on master
```

A note on `merge --squash` for cleaner histories: https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

In the case of our offline, _sort of_ testing branch, if it is indeed master we could revert with one simple step backwards.

## Anyways...

```
master -> feature -> feature-PR -> * -> master (merge --squash)

* additional manual checking may occur here
```

This is basically just "GitHub Flow": https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf#a5c2

I expect that our "advanced git branch structure" (#12) will likely take the form of "GitLab Flow" also found in the above document. But for now... this is the approach. GitHub Flow

## To the problem at hand...

This means our git behaviour will look like this:

```
master -> feature -> feature-pr -> master
```

It's at that last step we still need to intercept the process and create our release branches. As I suggested above, we might use GitLab Flow to achieve that... These are the rules:

1. Deployments are automatic, based on branches or tags.
2. Tags are set by the user, not by CI.
3. Releases are based on tags.

Will finalise in next comment... The gist is this:

1. Tag a commit on `master`
2. Have CI generate release branch from tag (?? probably)

**Comment by thombruce** [comment]
Tags and releases are effectively the same thing. In GitHub, a release is a tag that may or may not have additional resources made available for download.

There is some utility to this for Hugo themes. A release could have a `.zip` with the theme or extension at that point in its lifetime.

However, a more favourable approach remains to have a "release branch" that can be pointed to like any other Git submodule.

## Travis CI

Some documentation on uploading files when a tagged release is built by Travis CI: https://docs.travis-ci.com/user/deployment/releases

See also: My Travis CI config for pushing a Hugo build to an entirely separate repo - https://gist.github.com/thombruce/15c1db3b1bf98648f4f1070e755cdc24

### What needs to happen

On a tagged build...

1. Zip up the repo contents
2. Upload to tagged GitHub release

And

1. Checkout a new branch named for tag
2. Push new "release branch" to repo

### Basic Travis CI tag deploy config

```yaml
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
```

### My Hugo 'Deploy to Repo' config

```yaml
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  repo: [user/organization]/[user/organization].github.io
  allow-empty-commit: true
  target-branch: master
  on:
    branch: master
```

### Deploying to Multiple Providers

Totally possible: https://docs.travis-ci.com/user/deployment/#deploying-to-multiple-providers

There are some notable discrepancies above, but the biggest is the separate providers.

But...

Our second consideration is not actually a supported deployment method.

### Pushing back to GitHub

It's a push back to GitHub...

So here's a bit about custom deployment: https://docs.travis-ci.com/user/deployment/custom/

And here's a suggested method for pushing back to git: https://gist.github.com/willprice/e07efd73fb7f13f917ea

Ideally, produce some config that minimises the steps involved and keeps it in the Travis file. Of course, if it does become too verbose do move it into a separate script file. But I think we can avoid that.

**Comment by thombruce** [comment]
(master -> feature -> PR -> master)_*n_ **-> tag -> CI -> 0.1**

**Comment by thombruce** [comment]
Closed at 3ae98b743a1912b29da72410f264e1fd4428fd42

Basic Travis CI config:

```yaml
language: minimal

os: osx

before_install:
  - chmod +x bin/hugo

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - cd exampleSite
        - ../bin/hugo --themesDir ../../ --theme hugomodo
    - stage: deploy
      script:
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - release_branch=$(echo ${TRAVIS_TAG} | cut -b 2-)
        - git checkout -b $release_branch
        - git push -u origin $release_branch
```

This will need modification for #12 the advanced config. Mainly... the test stage. How will we handle the notion of theme inheritance? Perhaps we can clone directly into the necessary directory (**NOTE**: the one signified by themesDir, not the expected one relative to exampleSite).
